apiVersion: apps/v1
kind: Deployment
metadata:
  name: pat-judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pat-judge
  template:
    metadata:
      labels:
        app: pat-judge
    spec:
      hostNetwork: true
      containers:
        - name: pat-judge
          image: pat-judge:{VERSION}
          envFrom:
            - configMapRef:
                name: pat-config
          volumeMounts:
            - name: problem-volume
              mountPath: /problem
            - name: submission-volume
              mountPath: /submission
            - name: log-volume
              mountPath: /log
      volumes:
        - name: submission-volume
          hostPath:
            path: /home/tonix/dev/patpat/volume/bucket/submission
            type: Directory
        - name: problem-volume
          hostPath:
            path: /home/tonix/dev/patpat/volume/bucket/problem
            type: Directory
        - name: log-volume
          hostPath:
            path: /home/tonix/dev/patpat/volume/log
            type: Directory
